version: '3'

services:
  web:
    build: .
    command: npm run debug
    volumes:
      - ./build:/server/build
    ports:
      - 3000:${PORT}
      - 9229:9229
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5444:5432
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
# this process could be improved by using shell scripts which *actually*
# wait for the processes to be ready
