version: '3'

services:
  web:
    build: .
    command: npm run debug
    volumes:
      - ./build:/server/build
    ports:
      - 3000:${PORT}
      - 9229:9229
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5444:5432
    env_file:
      - .env
