version: '3'

services:
  sut:
    build: .
    command: npm test
    volumes:
      - ./build:/server/build
    depends_on:
      - test_db
    env_file:
      - test.env
  test_db:
    image: postgres
    restart: always
    ports:
      - 5444:5432
    env_file:
      - test.env
# this process could be improved by using shell scripts which *actually*
# wait for the processes to be ready
